version: "3.9"

services:
  frontend:
    platform: linux/x86_64
    container_name: sharenergy_frontend
    build: ./front-end
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    platform: linux/x86_64
    container_name: sharenergy_backend
    build: ./back-end
    working_dir: /api
    ports:
      - 3333:3333
    environment:
      - MONGO_URI=mongodb://localhost:27017/sharenergy_db
      - PORT=3333
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.3
    container_name: sharenergy_db
    platform: linux/x86_64
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: sharenergy_net
